apiVersion: apps/v1
kind: Deployment
metadata:
  name: home3-live
#  specification
spec:
  #  副本数量
  replicas: 3
  selector:
    matchLabels:
      app: home3-live
  #      template 描述的是你的 POD 是什么样的keb
  template:
    metadata:
      labels:
        app: home3-live
    #    POD 的具体信息
    spec:
      containers:
        - name: home3
          image: lee/home3-live:v0.0.1
          ports:
            - containerPort: 8080
