.PHONY: docker
docker:
	@rm home3 || ture
	#windows 这么写报错 (GOOS=linux GOARCH=arm go build -o home3 .) 所以改成了下面这个
	@set GOOS=linux
	@set GOARCH=arm
	@go build -o home3 .
	@docker rmi -f lee/home3:v.0.0.1
	@docker build -t lee/home3:v0.0.1